import type { Metadata } from "next";
import "./globals.css";

import Particles from "@/ui/design-system/particles/Particles"

export const metadata: Metadata = {
  title: "Portfolio Alexis Joncour",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        {children}
      </body>
    </html>
  );
}
